
# Group by apply

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

pd.set_option('display.max_rows', 500)

# All functions requires DataFrames with sorted date

In [2]:
pd_JH_data = pd.read_csv(r"C:\Users\pinak savaliya\eds_covid-19_analysis\data\processed\COVID_relational_confirmed.csv", sep = ';', parse_dates = [0])
pd_JH_data = pd_JH_data.sort_values('date', ascending = True).reset_index(drop = True).copy()
pd_JH_data.head()

        date    state     country  confirmed
0 2020-01-22  Alberta      Canada        0.0
1 2020-01-22       no      Kosovo        0.0
2 2020-01-22       no      Kuwait        0.0
3 2020-01-22       no  Kyrgyzstan        0.0
4 2020-01-22       no        Laos        0.0

# Test-data

In [3]:
test_data = pd_JH_data[((pd_JH_data['country']=='US')|
                       (pd_JH_data['country'] == 'Germany'))&
                      (pd_JH_data['date']<'2020-04-20')]
test_data

            date state  country  confirmed
41    2020-01-22    no  Germany        0.0
89    2020-01-22    no       US        1.0
323   2020-01-23    no  Germany        0.0
374   2020-01-23    no       US        1.0
609   2020-01-24    no  Germany        0.0
659   2020-01-24    no       US        2.0
894   2020-01-25    no  Germany        0.0
944   2020-01-25    no       US        2.0
1180  2020-01-26    no  Germany        0.0
1229  2020-01-26    no       US        5.0
1464  2020-01-27    no  Germany        1.0
1514  2020-01-27    no       US        5.0
1749  2020-01-28    no  Germany        4.0
1799  2020-01-28    no       US        5.0
2035  2020-01-29    no  Germany        4.0
2084  2020-01-29    no       US        6.0
2319  2020-01-30    no  Germany        4.0
2369  2020-01-30    no       US        6.0
2604  2020-01-31    no  Germany        5.0
2654  2020-01-31    no       US        8.0
2889  2020-02-01    no  Germany        8.0
2953  2020-02-01    no       US        8.0
3175  2020-02-02    no  Germany       10.0
3223  2020-02-02    no       US        8.0
3460  2020-02-03    no  Germany       12.0
3523  2020-02-03    no       US       11.0
3744  2020-02-04    no  Germany       12.0
3794  2020-02-04    no       US       11.0
4030  2020-02-05    no  Germany       12.0
4079  2020-02-05    no       US       11.0
4314  2020-02-06    no  Germany       12.0
4364  2020-02-06    no       US       12.0
4600  2020-02-07    no  Germany       13.0
4656  2020-02-07    no       US       12.0
4885  2020-02-08    no  Germany       13.0
4934  2020-02-08    no       US       12.0
5170  2020-02-09    no  Germany       14.0
5226  2020-02-09    no       US       12.0
5455  2020-02-10    no  Germany       14.0
5503  2020-02-10    no       US       12.0
5739  2020-02-11    no  Germany       16.0
5789  2020-02-11    no       US       13.0
6024  2020-02-12    no  Germany       16.0
6088  2020-02-12    no       US       13.0
6309  2020-02-13    no  Germany       16.0
6359  2020-02-13    no       US       14.0
6594  2020-02-14    no  Germany       16.0
6644  2020-02-14    no       US       14.0
6879  2020-02-15    no  Germany       16.0
6943  2020-02-15    no       US       14.0
7165  2020-02-16    no  Germany       16.0
7213  2020-02-16    no       US       14.0
7450  2020-02-17    no  Germany       16.0
7513  2020-02-17    no       US       14.0
7734  2020-02-18    no  Germany       16.0
7784  2020-02-18    no       US       14.0
8020  2020-02-19    no  Germany       16.0
8069  2020-02-19    no       US       14.0
8304  2020-02-20    no  Germany       16.0
8354  2020-02-20    no       US       14.0
8589  2020-02-21    no  Germany       16.0
8646  2020-02-21    no       US       16.0
8874  2020-02-22    no  Germany       16.0
8924  2020-02-22    no       US       16.0
9160  2020-02-23    no  Germany       16.0
9209  2020-02-23    no       US       16.0
9444  2020-02-24    no  Germany       16.0
9494  2020-02-24    no       US       16.0
9729  2020-02-25    no  Germany       16.0
9779  2020-02-25    no       US       16.0
10014 2020-02-26    no  Germany       21.0
10063 2020-02-26    no       US       16.0
10299 2020-02-27    no  Germany       26.0
10349 2020-02-27    no       US       17.0
10584 2020-02-28    no  Germany       53.0
10634 2020-02-28    no       US       17.0
10869 2020-02-29    no  Germany       66.0
10933 2020-02-29    no       US       25.0
11155 2020-03-01    no  Germany      117.0
11203 2020-03-01    no       US       32.0
11440 2020-03-02    no  Germany      150.0
11503 2020-03-02    no       US       55.0
11724 2020-03-03    no  Germany      188.0
11774 2020-03-03    no       US       74.0
12009 2020-03-04    no  Germany      240.0
12073 2020-03-04    no       US      107.0
12294 2020-03-05    no  Germany      349.0
12344 2020-03-05    no       US      184.0
12580 2020-03-06    no  Germany      534.0
12636 2020-03-06    no       US      237.0
12865 2020-03-07    no  Germany      684.0
12914 2020-03-07    no       US      403.0
13150 2020-03-08    no  Germany      847.0
13206 2020-03-08    no       US      519.0
13435 2020-03-09    no  Germany     1112.0
13483 2020-03-09    no       US      594.0
13719 2020-03-10    no  Germany     1296.0
13769 2020-03-10    no       US      782.0
14004 2020-03-11    no  Germany     1567.0
14068 2020-03-11    no       US     1147.0
14289 2020-03-12    no  Germany     2369.0
14339 2020-03-12    no       US     1586.0
14574 2020-03-13    no  Germany     3062.0
14624 2020-03-13    no       US     2219.0
14859 2020-03-14    no  Germany     3795.0
14923 2020-03-14    no       US     2978.0
15145 2020-03-15    no  Germany     4838.0
15193 2020-03-15    no       US     3212.0
15430 2020-03-16    no  Germany     6012.0
15493 2020-03-16    no       US     4679.0
15714 2020-03-17    no  Germany     7156.0
15764 2020-03-17    no       US     6512.0
15999 2020-03-18    no  Germany     8198.0
16049 2020-03-18    no       US     9169.0
16284 2020-03-19    no  Germany    10999.0
16334 2020-03-19    no       US    13663.0
16569 2020-03-20    no  Germany    13957.0
16619 2020-03-20    no       US    20030.0
16854 2020-03-21    no  Germany    16662.0
16918 2020-03-21    no       US    26025.0
17140 2020-03-22    no  Germany    18610.0
17188 2020-03-22    no       US    34944.0
17425 2020-03-23    no  Germany    22672.0
17488 2020-03-23    no       US    46096.0
17709 2020-03-24    no  Germany    27436.0
17759 2020-03-24    no       US    56714.0
17995 2020-03-25    no  Germany    31554.0
18044 2020-03-25    no       US    68841.0
18279 2020-03-26    no  Germany    36508.0
18329 2020-03-26    no       US    86662.0
18564 2020-03-27    no  Germany    42288.0
18614 2020-03-27    no       US   105253.0
18849 2020-03-28    no  Germany    48582.0
18913 2020-03-28    no       US   127417.0
19135 2020-03-29    no  Germany    52547.0
19183 2020-03-29    no       US   143544.0
19420 2020-03-30    no  Germany    57298.0
19483 2020-03-30    no       US   165698.0
19704 2020-03-31    no  Germany    61913.0
19754 2020-03-31    no       US   192079.0
19990 2020-04-01    no  Germany    67366.0
20039 2020-04-01    no       US   223254.0
20274 2020-04-02    no  Germany    73522.0
20324 2020-04-02    no       US   255530.0
20559 2020-04-03    no  Germany    79696.0
20609 2020-04-03    no       US   287931.0
20844 2020-04-04    no  Germany    85778.0
20908 2020-04-04    no       US   319776.0
21130 2020-04-05    no  Germany    91714.0
21178 2020-04-05    no       US   349016.0
21415 2020-04-06    no  Germany    95391.0
21478 2020-04-06    no       US   380798.0
21699 2020-04-07    no  Germany    99225.0
21749 2020-04-07    no       US   410834.0
21985 2020-04-08    no  Germany   103228.0
22034 2020-04-08    no       US   441897.0
22269 2020-04-09    no  Germany   108202.0
22319 2020-04-09    no       US   477507.0
22554 2020-04-10    no  Germany   113525.0
22604 2020-04-10    no       US   511790.0
22839 2020-04-11    no  Germany   117658.0
22903 2020-04-11    no       US   540714.0
23125 2020-04-12    no  Germany   120479.0
23173 2020-04-12    no       US   567022.0
23410 2020-04-13    no  Germany   123016.0
23473 2020-04-13    no       US   594165.0
23694 2020-04-14    no  Germany   125098.0
23744 2020-04-14    no       US   622493.0
23979 2020-04-15    no  Germany   127584.0
24043 2020-04-15    no       US   648390.0
24264 2020-04-16    no  Germany   130450.0
24314 2020-04-16    no       US   678028.0
24549 2020-04-17    no  Germany   133830.0
24599 2020-04-17    no       US   711135.0
24834 2020-04-18    no  Germany   137439.0
24898 2020-04-18    no       US   738464.0
25120 2020-04-19    no  Germany   139897.0
25168 2020-04-19    no       US   763886.0

In [4]:
test_data.groupby(['country']).agg(np.max)    # returns max values for groupped entities. i.e. 'US' and 'Germany'

              date state  confirmed
country
Germany 2020-04-19    no   139897.0
US      2020-04-19    no   763886.0

In [5]:
import numpy as np
import pandas as pd
from sklearn import linear_model
reg = linear_model.LinearRegression(fit_intercept = True)

def get_doubling_time_via_regression(in_array):
    ''' Use of linear regression to get doubling rate'''
    y = np.array(in_array)
    X = np.arange(-1, 2).reshape(-1, 1)
    
    assert len(in_array) == 3
    
    reg.fit(X,y)
    intercept = reg.intercept_
    slope = reg.coef_
    
    return intercept/slope

if __name__ == '__main__':                   
    test_data2 = np.array([2,4,6])
    result = get_doubling_time_via_regression(test_data2)
    print('the test slope is: '+str(result))

the test slope is: [2.]

In [6]:
test_data.groupby(['state', 'country']).agg(np.max)    # returns a dataframe with 2 indices

                    date  confirmed
state country
no    Germany 2020-04-19   139897.0
      US      2020-04-19   763886.0

In [7]:
def rolling_reg(df_input, col = 'confirmed'):
    ''' input has to be a data frame
    return is single series (mandatory for group by apply)'''
    days_back = 3
    result = df_input[col].rolling(
                    window = days_back,
                    min_periods = days_back).apply(get_doubling_time_via_regression, raw = False)
# rolling is a loop function which selects values equal to 'window size' successively throughout the series.   
    return result

In [8]:
test_data[['state', 'country', 'confirmed']].groupby(['state', 'country']).apply(rolling_reg, 'confirmed')

state  country
no     Germany  41             NaN
                323            NaN
                609            NaN
                894            NaN
                1180           NaN
                1464      0.666667
                1749      0.833333
                2035      2.000000
                2319           inf
                2604      8.666667
                2889      2.833333
                3175      3.066667
                3460      5.000000
                3744     11.333333
                4030           inf
                4314           inf
                4600     24.666667
                4885     25.333333
                5170     26.666667
                5455     27.333333
                5739     14.666667
                6024     15.333333
                6309           inf
                6594           inf
                6879           inf
                7165           inf
                7450           inf
                7734           inf
                8020           inf
                8304           inf
                8589           inf
                8874           inf
                9160           inf
                9444           inf
                9729           inf
                10014     7.066667
                10299     4.200000
                10584     2.083333
                10869     2.416667
                11155     2.458333
                11440     2.642857
                11724     4.272300
                12009     4.281481
                12294     3.217391
                12580     2.546485
                12865     3.118408
                13150     4.398296
                13435     4.116822
                13719     4.832962
                14004     5.824176
                14289     3.250699
                14574     3.120624
                14859     4.313230
                15145     4.390015
                15430     4.403849
                15714     5.178602
                15999     6.516011
                16284     4.571602
                16569     3.837935
                16854     4.899405
                17140     7.053371
                17425     6.427510
                17709     5.190573
                17995     6.129400
                18279     7.017784
                18564     6.853612
                18849     7.033184
                19135     9.319752
                19420    12.117715
                19704    12.225639
                19990    12.354456
                20274    11.646194
                20559    11.926683
                20844    13.000218
                21130    14.266822
                21415    18.924581
                21699    25.414281
                21985    25.336566
                22269    23.070439
                22554    21.038814
                22839    23.927312
                23125    33.713163
                23410    44.936295
                23694    53.199538
                23979    54.830414
                24264    47.724464
                24549    41.825595
                24834    38.319168
                25120    45.180594
       US       89             NaN
                374            NaN
                659       2.666667
                944       3.333333
                1229      2.000000
                1514      2.666667
                1799           inf
                2084     10.666667
                2369     11.333333
                2654      6.666667
                2953      7.333333
                3223           inf
                3523      6.000000
                3794      6.666667
                4079           inf
                4364     22.666667
                4656     23.333333
                4934           inf
                5226           inf
                5503           inf
                5789     24.666667
                6088     25.333333
                6359     26.666667
                6644     27.333333
                6943           inf
                7213           inf
                7513           inf
                7784           inf
                8069           inf
                8354           inf
                8646     14.666667
                8924     15.333333
                9209           inf
                9494           inf
                9779           inf
                10063          inf
                10349    32.666667
                10634    33.333333
                10933     4.916667
                11203     3.288889
                11503     2.488889
                11774     2.555556
                12073     3.025641
                12344     2.212121
                12636     2.707692
                12914     2.508371
                13206     2.739953
                13483     5.291449
                13769     4.803549
                14068     3.041591
                14339     2.914594
                14624     3.079602
                14923     3.248563
                15193     5.645519
                15493     4.259847
                15764     2.909697
                16049     3.023014
                16334     2.735655
                16619     2.630943
                16918     3.220514
                17188     3.620714
                17488     3.556209
                17759     4.218466
                18044     5.031172
                18329     4.724122
                18614     4.774177
                18913     5.223604
                19183     6.550086
                19483     7.604451
                19754     6.886041
                20039     6.730037
                20324     7.048620
                20609     7.903015
                20908     8.957621
                21178    10.441440
                21478    11.466793
                21749    12.301142
                22034    13.459347
                22319    13.301116
                22604    13.651286
                22903    16.137569
                23173    19.548160
                23473    21.226931
                23744    21.436787
                24043    22.929743
                24314    23.395588
                24599    21.649034
                24898    23.469753
                25168    27.974004
Name: confirmed, dtype: float64

In [9]:
test_data

            date state  country  confirmed
41    2020-01-22    no  Germany        0.0
89    2020-01-22    no       US        1.0
323   2020-01-23    no  Germany        0.0
374   2020-01-23    no       US        1.0
609   2020-01-24    no  Germany        0.0
659   2020-01-24    no       US        2.0
894   2020-01-25    no  Germany        0.0
944   2020-01-25    no       US        2.0
1180  2020-01-26    no  Germany        0.0
1229  2020-01-26    no       US        5.0
1464  2020-01-27    no  Germany        1.0
1514  2020-01-27    no       US        5.0
1749  2020-01-28    no  Germany        4.0
1799  2020-01-28    no       US        5.0
2035  2020-01-29    no  Germany        4.0
2084  2020-01-29    no       US        6.0
2319  2020-01-30    no  Germany        4.0
2369  2020-01-30    no       US        6.0
2604  2020-01-31    no  Germany        5.0
2654  2020-01-31    no       US        8.0
2889  2020-02-01    no  Germany        8.0
2953  2020-02-01    no       US        8.0
3175  2020-02-02    no  Germany       10.0
3223  2020-02-02    no       US        8.0
3460  2020-02-03    no  Germany       12.0
3523  2020-02-03    no       US       11.0
3744  2020-02-04    no  Germany       12.0
3794  2020-02-04    no       US       11.0
4030  2020-02-05    no  Germany       12.0
4079  2020-02-05    no       US       11.0
4314  2020-02-06    no  Germany       12.0
4364  2020-02-06    no       US       12.0
4600  2020-02-07    no  Germany       13.0
4656  2020-02-07    no       US       12.0
4885  2020-02-08    no  Germany       13.0
4934  2020-02-08    no       US       12.0
5170  2020-02-09    no  Germany       14.0
5226  2020-02-09    no       US       12.0
5455  2020-02-10    no  Germany       14.0
5503  2020-02-10    no       US       12.0
5739  2020-02-11    no  Germany       16.0
5789  2020-02-11    no       US       13.0
6024  2020-02-12    no  Germany       16.0
6088  2020-02-12    no       US       13.0
6309  2020-02-13    no  Germany       16.0
6359  2020-02-13    no       US       14.0
6594  2020-02-14    no  Germany       16.0
6644  2020-02-14    no       US       14.0
6879  2020-02-15    no  Germany       16.0
6943  2020-02-15    no       US       14.0
7165  2020-02-16    no  Germany       16.0
7213  2020-02-16    no       US       14.0
7450  2020-02-17    no  Germany       16.0
7513  2020-02-17    no       US       14.0
7734  2020-02-18    no  Germany       16.0
7784  2020-02-18    no       US       14.0
8020  2020-02-19    no  Germany       16.0
8069  2020-02-19    no       US       14.0
8304  2020-02-20    no  Germany       16.0
8354  2020-02-20    no       US       14.0
8589  2020-02-21    no  Germany       16.0
8646  2020-02-21    no       US       16.0
8874  2020-02-22    no  Germany       16.0
8924  2020-02-22    no       US       16.0
9160  2020-02-23    no  Germany       16.0
9209  2020-02-23    no       US       16.0
9444  2020-02-24    no  Germany       16.0
9494  2020-02-24    no       US       16.0
9729  2020-02-25    no  Germany       16.0
9779  2020-02-25    no       US       16.0
10014 2020-02-26    no  Germany       21.0
10063 2020-02-26    no       US       16.0
10299 2020-02-27    no  Germany       26.0
10349 2020-02-27    no       US       17.0
10584 2020-02-28    no  Germany       53.0
10634 2020-02-28    no       US       17.0
10869 2020-02-29    no  Germany       66.0
10933 2020-02-29    no       US       25.0
11155 2020-03-01    no  Germany      117.0
11203 2020-03-01    no       US       32.0
11440 2020-03-02    no  Germany      150.0
11503 2020-03-02    no       US       55.0
11724 2020-03-03    no  Germany      188.0
11774 2020-03-03    no       US       74.0
12009 2020-03-04    no  Germany      240.0
12073 2020-03-04    no       US      107.0
12294 2020-03-05    no  Germany      349.0
12344 2020-03-05    no       US      184.0
12580 2020-03-06    no  Germany      534.0
12636 2020-03-06    no       US      237.0
12865 2020-03-07    no  Germany      684.0
12914 2020-03-07    no       US      403.0
13150 2020-03-08    no  Germany      847.0
13206 2020-03-08    no       US      519.0
13435 2020-03-09    no  Germany     1112.0
13483 2020-03-09    no       US      594.0
13719 2020-03-10    no  Germany     1296.0
13769 2020-03-10    no       US      782.0
14004 2020-03-11    no  Germany     1567.0
14068 2020-03-11    no       US     1147.0
14289 2020-03-12    no  Germany     2369.0
14339 2020-03-12    no       US     1586.0
14574 2020-03-13    no  Germany     3062.0
14624 2020-03-13    no       US     2219.0
14859 2020-03-14    no  Germany     3795.0
14923 2020-03-14    no       US     2978.0
15145 2020-03-15    no  Germany     4838.0
15193 2020-03-15    no       US     3212.0
15430 2020-03-16    no  Germany     6012.0
15493 2020-03-16    no       US     4679.0
15714 2020-03-17    no  Germany     7156.0
15764 2020-03-17    no       US     6512.0
15999 2020-03-18    no  Germany     8198.0
16049 2020-03-18    no       US     9169.0
16284 2020-03-19    no  Germany    10999.0
16334 2020-03-19    no       US    13663.0
16569 2020-03-20    no  Germany    13957.0
16619 2020-03-20    no       US    20030.0
16854 2020-03-21    no  Germany    16662.0
16918 2020-03-21    no       US    26025.0
17140 2020-03-22    no  Germany    18610.0
17188 2020-03-22    no       US    34944.0
17425 2020-03-23    no  Germany    22672.0
17488 2020-03-23    no       US    46096.0
17709 2020-03-24    no  Germany    27436.0
17759 2020-03-24    no       US    56714.0
17995 2020-03-25    no  Germany    31554.0
18044 2020-03-25    no       US    68841.0
18279 2020-03-26    no  Germany    36508.0
18329 2020-03-26    no       US    86662.0
18564 2020-03-27    no  Germany    42288.0
18614 2020-03-27    no       US   105253.0
18849 2020-03-28    no  Germany    48582.0
18913 2020-03-28    no       US   127417.0
19135 2020-03-29    no  Germany    52547.0
19183 2020-03-29    no       US   143544.0
19420 2020-03-30    no  Germany    57298.0
19483 2020-03-30    no       US   165698.0
19704 2020-03-31    no  Germany    61913.0
19754 2020-03-31    no       US   192079.0
19990 2020-04-01    no  Germany    67366.0
20039 2020-04-01    no       US   223254.0
20274 2020-04-02    no  Germany    73522.0
20324 2020-04-02    no       US   255530.0
20559 2020-04-03    no  Germany    79696.0
20609 2020-04-03    no       US   287931.0
20844 2020-04-04    no  Germany    85778.0
20908 2020-04-04    no       US   319776.0
21130 2020-04-05    no  Germany    91714.0
21178 2020-04-05    no       US   349016.0
21415 2020-04-06    no  Germany    95391.0
21478 2020-04-06    no       US   380798.0
21699 2020-04-07    no  Germany    99225.0
21749 2020-04-07    no       US   410834.0
21985 2020-04-08    no  Germany   103228.0
22034 2020-04-08    no       US   441897.0
22269 2020-04-09    no  Germany   108202.0
22319 2020-04-09    no       US   477507.0
22554 2020-04-10    no  Germany   113525.0
22604 2020-04-10    no       US   511790.0
22839 2020-04-11    no  Germany   117658.0
22903 2020-04-11    no       US   540714.0
23125 2020-04-12    no  Germany   120479.0
23173 2020-04-12    no       US   567022.0
23410 2020-04-13    no  Germany   123016.0
23473 2020-04-13    no       US   594165.0
23694 2020-04-14    no  Germany   125098.0
23744 2020-04-14    no       US   622493.0
23979 2020-04-15    no  Germany   127584.0
24043 2020-04-15    no       US   648390.0
24264 2020-04-16    no  Germany   130450.0
24314 2020-04-16    no       US   678028.0
24549 2020-04-17    no  Germany   133830.0
24599 2020-04-17    no       US   711135.0
24834 2020-04-18    no  Germany   137439.0
24898 2020-04-18    no       US   738464.0
25120 2020-04-19    no  Germany   139897.0
25168 2020-04-19    no       US   763886.0

# Filtering the data with groupby apply

In [10]:
pd_DR_result=pd_JH_data[['state','country','confirmed']].groupby(['state','country']).apply(rolling_reg,'confirmed').reset_index()

In [11]:
pd_DR_result

          state   country  level_2     confirmed
0       Alberta    Canada        0           NaN
1       Alberta    Canada      499           NaN
2       Alberta    Canada      762           NaN
3       Alberta    Canada     1048           NaN
4       Alberta    Canada     1354           NaN
...         ...       ...      ...           ...
259915       no  Zimbabwe   258586           inf
259916       no  Zimbabwe   258828           inf
259917       no  Zimbabwe   259156  4.925340e+03
259918       no  Zimbabwe   259398  4.926006e+03
259919       no  Zimbabwe   259919  1.707980e+04

[259920 rows x 4 columns]

In [12]:
pd_DR_result=pd_DR_result.rename(columns={'confirmed':'doubling_rate','level_2':'index'})
pd_DR_result.head()

     state country  index  doubling_rate
0  Alberta  Canada      0            NaN
1  Alberta  Canada    499            NaN
2  Alberta  Canada    762            NaN
3  Alberta  Canada   1048            NaN
4  Alberta  Canada   1354            NaN

In [13]:
pd_JH_data = pd_JH_data.reset_index()
pd_JH_data.head()

   index       date    state     country  confirmed
0      0 2020-01-22  Alberta      Canada        0.0
1      1 2020-01-22       no      Kosovo        0.0
2      2 2020-01-22       no      Kuwait        0.0
3      3 2020-01-22       no  Kyrgyzstan        0.0
4      4 2020-01-22       no        Laos        0.0

In [14]:
pd.merge(pd_JH_data, pd_DR_result, on = ['index'], how = 'left')

,index,date,state_x,country_x,confirmed,state_y,country_y,doubling_rate
0,0,2020-01-22,Alberta,Canada,0.0,Alberta,Canada,NaN
1,1,2020-01-22,no,Kosovo,0.0,no,Kosovo,NaN
2,2,2020-01-22,no,Kuwait,0.0,no,Kuwait,NaN
3,3,2020-01-22,no,Kyrgyzstan,0.0,no,Kyrgyzstan,NaN
4,4,2020-01-22,no,Laos,0.0,no,Laos,NaN
...,...,...,...,...,...,...,...,...
259915,259915,2022-07-21,no,Andorra,45326.0,no,Andorra,3.407497e+02
259916,259916,2022-07-21,no,Algeria,266654.0,no,Algeria,4.760637e+03
259917,259917,2022-07-21,no,Albania,293917.0,no,Albania,inf
259918,259918,2022-07-21,no,Argentina,9465827.0,no,Argentina,inf
259919,259919,2022-07-21,no,Zimbabwe,256217.0,no,Zimbabwe,1.707980e+04

In [15]:
pd_result_larg=pd.merge(pd_JH_data,pd_DR_result[['index','doubling_rate']],on=['index'],how='left')
pd_result_larg.head()

   index       date    state     country  confirmed  doubling_rate
0      0 2020-01-22  Alberta      Canada        0.0            NaN
1      1 2020-01-22       no      Kosovo        0.0            NaN
2      2 2020-01-22       no      Kuwait        0.0            NaN
3      3 2020-01-22       no  Kyrgyzstan        0.0            NaN
4      4 2020-01-22       no        Laos        0.0            NaN

In [16]:
from scipy import signal

def savgol_filter(df_input,column='confirmed',window=5):
    ''' Savgol Filter which can be used in groupby apply function 
        it ensures that the data structure is kept'''
    window=5, 
    degree=1
    df_result=df_input   #'input_df' is stored into 'df_result' to avoid change in index during 'groupby' call. 
    
    filter_in=df_input[column].fillna(0) # attention with the neutral element here
    
    result=signal.savgol_filter(np.array(filter_in),
                           5, # window size used for filtering
                           1)
    df_result[column+'_filtered']=result
    return df_result

In [17]:
pd_filtered_result=pd_JH_data[['state','country','confirmed']].groupby(['state','country']).apply(savgol_filter).reset_index()

In [18]:
pd_result_larg=pd.merge(pd_result_larg,pd_filtered_result[['index','confirmed_filtered']],on=['index'],how='left')
pd_result_larg.head()

,index,date,state,country,confirmed,doubling_rate,confirmed_filtered
0,0,2020-01-22,Alberta,Canada,0.0,NaN,0.0
1,1,2020-01-22,no,Kosovo,0.0,NaN,0.0
2,2,2020-01-22,no,Kuwait,0.0,NaN,0.0
3,3,2020-01-22,no,Kyrgyzstan,0.0,NaN,0.0
4,4,2020-01-22,no,Laos,0.0,NaN,0.0

# Filtered Doubling Rate

In [20]:
pd_filtered_doubling=pd_result_larg[['state','country','confirmed_filtered']].groupby(['state','country']).apply(rolling_reg,'confirmed_filtered').reset_index()

pd_filtered_doubling=pd_filtered_doubling.rename(columns={'confirmed_filtered':'doubling_rate_filtered',
                             'level_2':'index'})

pd_filtered_doubling.tail()

       state   country   index  doubling_rate_filtered
259915    no  Zimbabwe  258586            10581.749311
259916    no  Zimbabwe  258828            10495.959016
259917    no  Zimbabwe  259156            10761.621849
259918    no  Zimbabwe  259398             8004.839583
259919    no  Zimbabwe  259919             6886.790323

In [21]:
pd_result_larg=pd.merge(pd_result_larg,pd_filtered_doubling[['index','doubling_rate_filtered']],on=['index'],how='left')
pd_result_larg.tail()

,index,date,state,country,confirmed,doubling_rate,confirmed_filtered,doubling_rate_filtered
259915,259915,2022-07-21,no,Andorra,45326.0,3.407497e+02,45298.0,3.447863e+02
259916,259916,2022-07-21,no,Algeria,266654.0,4.760637e+03,266648.2,5.107203e+03
259917,259917,2022-07-21,no,Albania,293917.0,inf,293917.0,-1.009891e+16
259918,259918,2022-07-21,no,Argentina,9465827.0,inf,9465827.0,-1.016385e+16
259919,259919,2022-07-21,no,Zimbabwe,256217.0,1.707980e+04,256225.8,6.886790e+03

In [22]:
pd_result_larg.head()

,index,date,state,country,confirmed,doubling_rate,confirmed_filtered,doubling_rate_filtered
0,0,2020-01-22,Alberta,Canada,0.0,NaN,0.0,NaN
1,1,2020-01-22,no,Kosovo,0.0,NaN,0.0,NaN
2,2,2020-01-22,no,Kuwait,0.0,NaN,0.0,NaN
3,3,2020-01-22,no,Kyrgyzstan,0.0,NaN,0.0,NaN
4,4,2020-01-22,no,Laos,0.0,NaN,0.0,NaN

In [23]:
pd_result_larg.to_csv(r'C:\Users\pinak savaliya\eds_covid-19_analysis\data\processed\COVID_final_set.csv',sep=';',index=False)